# Generated by Django 4.1.3 on 2022-12-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_order_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="merchant_id",
            new_name="payment_intent",
        ),
    ]
